language: ruby
rvm:
  - 2.7.1
  - jruby

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database development;' -U postgres
  - psql -c 'create database test;' -U postgres
  - psql -c 'create database production;' -U postgres

before_install:
  - rvm install 2.7.1
  - rvm use 2.7.1
